# Generated by Django 5.0.4 on 2024-04-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100)),
                ('author_nationality', models.CharField(max_length=100)),
                ('author_scholarship', models.TextField(max_length=500)),
                ('author_career', models.TextField(max_length=500)),
                ('author_award', models.TextField(max_length=500)),
            ],
        ),
    ]
