# Generated by Django 5.0.4 on 2024-05-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_intro',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_award',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_career',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_scholarship',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
