# Generated by Django 5.0.4 on 2024-06-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_author_intro_alter_author_author_award_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_award',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_career',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_scholarship',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
