# Generated by Django 5.0.4 on 2024-06-02 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.IntegerField(max_length=10)),
                ('purchase_book_isbn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book')),
                ('purchase_buyer_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.IntegerField(max_length=10)),
                ('sell_book_isbn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book')),
                ('sell_seller_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('trade_price', models.IntegerField(max_length=10)),
                ('trade_book_isbn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book')),
                ('trade_buyer_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_purchased', to=settings.AUTH_USER_MODEL)),
                ('trade_seller_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_sold', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
