# Generated by Django 5.0.4 on 2024-06-02 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='sell_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_price',
            field=models.IntegerField(),
        ),
    ]
