# Generated by Django 5.0.4 on 2024-04-27 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField(max_length=3000)),
                ('review_rating', models.SmallIntegerField(default=0)),
                ('review_like', models.SmallIntegerField(default=0)),
                ('review_book_isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('review_user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
